# Generated by Django 2.1 on 2021-11-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20211110_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cpassword',
            field=models.CharField(default='0000', max_length=10, verbose_name='cpassword'),
        ),
    ]
