# Generated by Django 2.1 on 2021-11-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_client_cpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='ccountry',
            field=models.CharField(choices=[('KOR', 'Korea'), ('USA', 'United State Of America'), ('JPN', 'Japen')], max_length=5, verbose_name='ccountry'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cpassword',
            field=models.CharField(max_length=10, verbose_name='cpassword'),
        ),
    ]
