# Generated by Django 2.1 on 2021-11-05 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
                ('cage', models.IntegerField(default=0)),
                ('ccountry', models.CharField(max_length=50)),
            ],
        ),
    ]
