# Generated by Django 2.1 on 2021-11-05 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0002_fuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fuser',
        ),
    ]
